services:
   nginx1:
    image: nginx
    ports: 
     - 8080:80
    volumes:
      - ./src/tp:/var/www/html
      - ./nginx:/etc/nginx/conf.d

   nginx2:
    image: nginx
    ports: 
     - 8081:80
    volumes:
      - ./src2/tp:/var/www/html
      - ./nginx2:/etc/nginx/conf.d

   php1:
      build: ./docker_file/php
      volumes:
         - './src/tp:/var/www/html'

   phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
         - 3000:80
      environment:
         - PMA_ARBITRARY=1
      depends_on:
         - db


   php2:
      build: ./docker_file/php
      volumes:
         - './src2/tp:/var/www/html'

   db:
      image: mysql:5.7
      volumes:
         - db_data:/var/lib/mysql
      restart: always
      ports:
         - 3307:3306
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: laravel
         MYSQL_USER: laravel
         MYSQL_PASSWORD: laravel
   
   composer :
      image: composer
      volumes:
         - './src/tp:/var/www/html'
      working_dir: /var/www/html
      command: composer install


   npm:
      image: node:alpine
      volumes:
         - './src/tp:/var/www/html'
      depends_on: 
         - composer
      working_dir: /var/www/html
      command: sh -c "npm install && npm run build"

volumes:
   db_data: {}

